<?php
/**
 * The garment, and how large you may print on it.
 *
 * The print zones are the reason this block exists. Neither mistertee.fr nor
 * tostadora.fr publishes a single print dimension on a product page (checked
 * 14 August 2026): Mistertee prices "1 à 4 faces" without ever saying how large
 * a face is, and Tostadora's 24 cm ceiling is buried in a help-centre article.
 * A buyer with a wide logo cannot plan on either. We can say it, because we
 * measure the ink rather than the file it arrived in.
 *
 * Every centimetre here was produced by the studio's own definitions
 * (data/garments.json, regenerated by scripts/gen-garment-data.mjs and gated by
 * src/content/garmentData.test.ts). Nothing on this page is typed by hand.
 *
 * Matière and grammage are shown only when a catalogue import has set them.
 * They exist nowhere in this project for these two references, and a fabric
 * composition invented for a layout is a fabric composition someone orders
 * against.
 *
 * @package Teeshoop\Core
 *
 * @var int    $product_id
 * @var string $garment
 * @var array  $areas       side, w, h at the priced size, plus by_size.
 * @var string $priced_size
 * @var array  $colors
 * @var array  $sizes
 * @var string $brand_ref
 * @var string $material
 * @var int    $weight_gsm
 * @var string $brand
 * @var string $brand_code
 * @var string $specs_date
 */

use Teeshoop\Core\Cart;
use Teeshoop\Core\Garments;
use Teeshoop\Core\Money;

defined( 'ABSPATH' ) || exit;

$ts_last_size = ! empty( $sizes ) ? (string) ( end( $sizes )['size'] ?? '' ) : '';
?>
<section class="ts-specs" id="ts-caracteristiques">

	<?php if ( ! empty( $areas ) ) : ?>
		<h2 class="ts-specs__title"><?php esc_html_e( 'Zones d’impression', 'teeshoop' ); ?></h2>

		<table class="ts-table ts-table--areas">
			<caption class="ts-table__caption">
				<?php
				printf(
					/* translators: %s: a garment size, e.g. M. */
					esc_html__( 'Surface imprimable maximale, mesurée sur une taille %s.', 'teeshoop' ),
					esc_html( $priced_size )
				);
				?>
			</caption>
			<tbody>
				<?php foreach ( $areas as $ts_area ) : ?>
					<tr>
						<th scope="row"><?php echo esc_html( Cart::side_label( (string) $ts_area['side'] ) ); ?></th>
						<td class="ts-num">
							<?php
							echo esc_html(
								Garments::cm( (float) $ts_area['w'] ) . "\u{00A0}×\u{00A0}" . Garments::cm( (float) $ts_area['h'] )
							);
							?>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>

		<?php
		$ts_first = $areas[0];
		$ts_grown = $ts_first['by_size'][ $ts_last_size ] ?? null;
		if ( '' !== $ts_last_size && is_array( $ts_grown ) ) :
			?>
			<p class="ts-note">
				<?php
				printf(
					/* translators: 1: side label, 2: the largest size, 3: that side's dimensions at that size. */
					/*
					 * QUALIFIED, because the studio has a control that turns it off.
					 *
					 * Every published per-size figure is the SCALED grading, which
					 * is the studio's default. A design switched to a single fixed
					 * transfer (the cheaper option the DTF panel recommends) keeps
					 * the base size on every garment, so the unqualified sentence
					 * was a promise the customer could break themselves.
					 */
					esc_html__( 'Quand le visuel est gradué avec le vêtement, ce qui est le réglage par défaut, la zone %1$s mesure %3$s sur un %2$s. En impression unique, il garde la même taille sur toutes les tailles.', 'teeshoop' ),
					esc_html( mb_strtolower( Cart::side_label( (string) $ts_first['side'] ) ) ),
					esc_html( $ts_last_size ),
					esc_html( Garments::cm( (float) $ts_grown['wCm'] ) . "\u{00A0}×\u{00A0}" . Garments::cm( (float) $ts_grown['hCm'] ) )
				);
				?>
			</p>
		<?php endif; ?>

		<p class="ts-note ts-note--strong">
			<?php esc_html_e( 'Vous payez la surface réellement imprimée, mesurée sur votre visuel. Un logo de 12 sur 8 centimètres est facturé comme un logo de 12 sur 8 centimètres, pas comme le fichier dans lequel il nous arrive.', 'teeshoop' ); ?>
		</p>
	<?php endif; ?>

	<h2 class="ts-specs__title"><?php esc_html_e( 'Le vêtement', 'teeshoop' ); ?></h2>
	<dl class="ts-defs">
		<?php if ( '' !== $brand ) : ?>
			<dt><?php esc_html_e( 'Marque', 'teeshoop' ); ?></dt>
			<dd><?php echo esc_html( $brand ); ?></dd>
		<?php endif; ?>

		<?php if ( '' !== $brand_code ) : ?>
			<dt><?php esc_html_e( 'Référence', 'teeshoop' ); ?></dt>
			<dd><?php echo esc_html( $brand_code ); ?></dd>
		<?php endif; ?>

		<?php if ( '' !== $material ) : ?>
			<dt><?php esc_html_e( 'Matière', 'teeshoop' ); ?></dt>
			<dd><?php echo esc_html( $material ); ?></dd>
		<?php endif; ?>

		<?php if ( $weight_gsm > 0 ) : ?>
			<dt><?php esc_html_e( 'Grammage', 'teeshoop' ); ?></dt>
			<dd class="ts-num"><?php echo esc_html( Money::number( (float) $weight_gsm ) . "\u{00A0}g/m²" ); ?></dd>
		<?php endif; ?>

		<?php if ( ! empty( $sizes ) ) : ?>
			<dt><?php esc_html_e( 'Tailles', 'teeshoop' ); ?></dt>
			<dd>
				<?php
				echo esc_html(
					implode(
						"\u{00A0}· ",
						array_map( static fn( array $r ): string => (string) $r['size'], $sizes )
					)
				);
				?>
			</dd>
		<?php endif; ?>

		<?php
		/*
		 * The colours are OURS, so they are shown only for a garment we supply.
		 *
		 * `Garments::colors()` is the shop-wide list, not a per-garment one, and
		 * it was rendered unconditionally. On a `custom` product, whose whole
		 * premise is that the customer ships their own shirt, the page held no
		 * zones, no sizes and no brand, and then told the buyer we stock it in
		 * eighteen colours. That is invented content on a product page.
		 */
		?>
		<?php if ( ! empty( $colors ) && Garments::has( $garment ) ) : ?>
			<dt><?php esc_html_e( 'Coloris', 'teeshoop' ); ?></dt>
			<dd>
				<ul class="ts-swatches">
					<?php foreach ( $colors as $ts_color ) : ?>
						<li class="ts-swatches__item">
							<span class="ts-swatches__chip" style="--ts-chip:<?php echo esc_attr( (string) $ts_color['hex'] ); ?>" aria-hidden="true"></span>
							<span class="ts-swatches__name"><?php echo esc_html( (string) $ts_color['name'] ); ?></span>
						</li>
					<?php endforeach; ?>
				</ul>
			</dd>
		<?php endif; ?>
	</dl>

	<?php if ( '' === $material && 0 === $weight_gsm && current_user_can( 'manage_woocommerce' ) ) : ?>
		<p class="ts-admin-note">
			<?php esc_html_e( 'Visible par vous seul : cet article ne porte ni matière ni grammage. Ils viennent des données fournisseur (séance 03) et la fiche préfère ne rien dire plutôt qu’inventer une composition.', 'teeshoop' ); ?>
		</p>
	<?php endif; ?>

	<?php if ( ! empty( $sizes ) ) : ?>
		<h2 class="ts-specs__title"><?php esc_html_e( 'Guide des tailles', 'teeshoop' ); ?></h2>
		<div class="ts-table__scroll">
			<table class="ts-table">
				<caption class="ts-table__caption">
					<?php
					if ( '' !== $brand_ref ) {
						printf(
							/* translators: %s: manufacturer and style reference the measurements come from. */
							esc_html__( 'Mesures à plat en centimètres, d’après %s.', 'teeshoop' ),
							esc_html( $brand_ref )
						);
					} else {
						esc_html_e( 'Mesures à plat, en centimètres.', 'teeshoop' );
					}
					?>
				</caption>
				<thead>
					<tr>
						<th scope="col"><?php esc_html_e( 'Taille', 'teeshoop' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Demi-poitrine', 'teeshoop' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Longueur', 'teeshoop' ); ?></th>
						<th scope="col"><?php esc_html_e( 'Manche', 'teeshoop' ); ?></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ( $sizes as $ts_row ) : ?>
						<tr>
							<th scope="row"><?php echo esc_html( (string) $ts_row['size'] ); ?></th>
							<td class="ts-num"><?php echo esc_html( Garments::cm( (float) $ts_row['halfChestCm'] ) ); ?></td>
							<td class="ts-num"><?php echo esc_html( Garments::cm( (float) $ts_row['bodyLengthCm'] ) ); ?></td>
							<td class="ts-num"><?php echo esc_html( Garments::cm( (float) $ts_row['sleeveLengthCm'] ) ); ?></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<p class="ts-note"><?php esc_html_e( 'La demi-poitrine se mesure d’une couture à l’autre, à plat, deux centimètres et demi sous l’emmanchure. Multipliez-la par deux pour le tour de poitrine.', 'teeshoop' ); ?></p>
	<?php endif; ?>

	<?php if ( '' !== $specs_date ) : ?>
		<p class="ts-note">
			<?php
			printf(
				/* translators: %s: the date the supplier data was captured. */
				esc_html__( 'Caractéristiques relevées le %s.', 'teeshoop' ),
				esc_html( $specs_date )
			);
			?>
		</p>
	<?php endif; ?>
</section>
